### PR TITLE
CV2-3589 minor tweak to expose another parameter

### PR DESCRIPTION
**Pull request by DGaffney**
## Description
Very minor ticket to allow us to pass an already-enabled parameter from check-api to fetch in order to specify a language identifier for incoming subscribed fetch articles.

References: CV2-3589

## How has this been tested?

No testing on this yet - this is only to be run directly in a backend repl to manually adjust a few workspaces. I wanted to make it a formal PR instead of just running it directly once so that we at least have the the parameter documented in the code should we need to do it again, or recall how we did it.

## Things to pay attention to during code review

Exposes `language` as a variable in `setup_service`, and then forwards that to fetch in a subsequent `POST` request.
## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Comment by computermacgyver** [comment]
This looks good to me. I think the one test I would make is to ensure that Fetch handles a `language = nil` parameter as intended and ignores `language` (i.e., we don't want Fetch to only return items with a `nil` value for language)

**Review by computermacgyver — APPROVED** [review]
LGTM pending the one point on testing how Fetch responds to a `language=nil` parameter in my other comment (and all unit tests successfully passing, which are still in progress at the point I'm writing this)

**Comment by DGaffney** [comment]
> Looks good assuming that:
> 
> * Tests pass
> * Fetch can handle a `nil` `language` parameter gracefully (as @computermacgyver pointed)... @DGaffney please confirm

On the fetch side, we *always* push language as a param into downstream functions, regardless of whether or not it was a present parameter:

```
  #lib/api.rb in Fetch:
  def self.add_subscription(params)
    Subscription.add_subscription(params[:service], params[:url], params[:language])
    Subscription.get_subscriptions(params[:service])
  end
```
So, since the inception of fetch, it's been nil - this would create no change on the fetch side - we're just finally using that as a parameter!

**Comment by caiosba** [comment]
> > Looks good assuming that:
> > 
> > * Tests pass
> > * Fetch can handle a `nil` `language` parameter gracefully (as @computermacgyver pointed)... @DGaffney please confirm
> 
> On the fetch side, we _always_ push language as a param into downstream functions, regardless of whether or not it was a present parameter:
> 
> ```
>   #lib/api.rb in Fetch:
>   def self.add_subscription(params)
>     Subscription.add_subscription(params[:service], params[:url], params[:language])
>     Subscription.get_subscriptions(params[:service])
>   end
> ```
> 
> So, since the inception of fetch, it's been nil - this would create no change on the fetch side - we're just finally using that as a parameter!

Thanks, good to go, then!

**Pull request merged**
