### PR TITLE
Epic/5571 bot preview

### PR DESCRIPTION
**Pull request by amoedoamorim**
## Description

I'm opening a new PR targeting `develop` as Jay's and Sawy's work was merged from a feature branch to this epic branch.

@caiosba and @melsawy can you please review and lmk if it's safe to merge? Just want to be extra sure as Jay's OOO today and tomorrrow.

### CODE REVIEW

**Comment by melsawy** [comment]
@amoedoamorim this PR also include my work I do not think it's save to merge this one into develop branch

**Comment by caiosba** [comment]
@amoedoamorim I think we'll need to wait for @melsawy's changes to be merged first.

**Review by caiosba — APPROVED** [review]
@amoedoamorim I rebased and fixed conflicts, changes look good to me - can you please test locally as well?

**Comment by amoedoamorim** [comment]
> @amoedoamorim I rebased and fixed conflicts, changes look good to me - can you please test locally as well?

Tested locally, works well. Merging!

**Pull request merged**
