### PR TITLE
CV2-3771: export published items without fact check to CSV file and copy reports to fact check

### PR DESCRIPTION
**Pull request by melsawy**
## Description

Add  two rake tasks:

1. `check:migrate:export_published_items_without_fact_check`: export published items without fact-check to CSV file
2. `check:migrate:set_fact_check_for_published_items`: create fact-check using report data for published items

References: CV2-3771

## How has this been tested?

Tested both rake tasks locally using a live DB dump.
1. `check:migrate:export_published_items_without_fact_check`:  Done in 19 minutes.
2. `check:migrate:set_fact_check_for_published_items`: Done in 36 minutes.  for a workspace contains **2586 items**

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Review by caiosba — COMMENTED** [review]
@melsawy , as we discussed, let's wait to see if we need to change this to actually convert reports to fact-checks.

**Review by caiosba — COMMENTED** [review]
Looks good Sawy, but just one question: for the rake task that copies information from report to fact check, you were not able to just call the existing method? You had to copy and paste?

**Comment by melsawy** [comment]
> Looks good Sawy, but just one question: for the rake task that copies information from report to fact check, you were not able to just call the existing method? You had to copy and paste?

yes @caiosba I could not call existing rake task as we running in different conditions the existing one loop in all `report_design` annotations but this rake task select only published reports without fact-check

**Review by caiosba — APPROVED** [review]
OK Sawy, thanks for the explanation.

**Pull request merged**
