### PR TITLE
test codeclimate report

### PR DESCRIPTION
**Pull request by chinelo-obitube**
## Description

fixing Codeclimate integration.

References: https://meedan.atlassian.net/browse/CV2-5315

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Review by caiosba — COMMENTED** [review]
Ah, I see the Code Climate check, great! @chinelo-obitube can you please confirm it is able to fail and add a comment if it finds anything?

**Comment by chinelo-obitube** [comment]
> Ah, I see the Code Climate check, great! @chinelo-obitube can you please confirm it is able to fail and add a comment if it finds anything?

It didnt add a comment or fail any error. still investigation why.

**Comment by chinelo-obitube** [comment]
> > > Ah, I see the Code Climate check, great! @chinelo-obitube can you please confirm it is able to fail and add a comment if it finds anything?
> > 
> > 
> > It didnt add a comment or fail any error. still investigation why.
> 
> Other things that should trigger an error: useless variable assignment, unused method argument...

now it works

**Comment by chinelo-obitube** [comment]
> > > > Ah, I see the Code Climate check, great! @chinelo-obitube can you please confirm it is able to fail and add a comment if it finds anything?
> > > 
> > > 
> > > It didnt add a comment or fail any error. still investigation why.
> > 
> > 
> > Other things that should trigger an error: useless variable assignment, unused method argument...
> 
> now it works

I will wait to see if it adds the error as comments

**Comment by caiosba** [comment]
Yay :tada:

**Comment by caiosba** [comment]
Oh, so actually there is nothing to approve/merge here, all the fix was on Code Climate side, right?

**Comment by chinelo-obitube** [comment]
yes it was on code climate side

**Comment by chinelo-obitube** [comment]
I will close this PR @caiosba .

**Pull request closed without merging**
