### PR TITLE
CV2-4853: fix sentry issue

### PR DESCRIPTION
**Pull request by melsawy**
## Description

Fix sentry issue.

References: CV2-4853

## How has this been tested?

Re-run automated tests.

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Review by caiosba — APPROVED** [review]

**Review by caiosba — CHANGES_REQUESTED** [review]
Sawy, can you please add a unit test for this?

**Comment by computermacgyver** [comment]
Thanks, @melsawy . This looks good. Since my commit was the last one on develop, I had reverted it, which is why the PR is showing a conflict for the merge. Thank you for cleaning up my mess and sorry for the trouble.

**Review by computermacgyver — APPROVED** [review]

**Review by caiosba — CHANGES_REQUESTED** [review]
@melsawy , by trying to fix the Code Climate issue, you surface two new ones :sweat_smile: 

And I think the code was less clear after that change... what do you think about updating our Code Climate configuration and bump from 22 to 23? -> https://github.com/meedan/check-api/blob/develop/.codeclimate.yml#L13

**Comment by melsawy** [comment]
> @melsawy , by trying to fix the Code Climate issue, you surface two new ones 😅
> 
> And I think the code was less clear after that change... what do you think about updating our Code Climate configuration and bump from 22 to 23? -> https://github.com/meedan/check-api/blob/develop/.codeclimate.yml#L13

Fixing new ones is simple but as you see the code was less clear I did another simple change for fixing CC

**Review by caiosba — APPROVED** [review]

**Pull request merged**
