### PR TITLE
CV2-2256 more options for search language filter in check

### PR DESCRIPTION
**Pull request by melsawy**
## Description

- Add ES mapping for request language.
- Allow user to filter by request language
- Rename ES methods by remove `build_search_` prefix  (i.e change `build_search_keyword_conditions` to `keyword_conditions`)
- Add ES mapping for report language

References:  CV2-2256

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Review by caiosba — APPROVED** [review]
Looks good, thanks for the renamings, it makes things much more clear. I just have one question: isn't it possible to have a rake task to index existing content?

**Comment by melsawy** [comment]
> I just have one question: isn't it possible to have a rake task to index existing content?
we already have a rake task to re-index nested field `bundle exec rails check:project_media:sync_es_nested_field['field:requests'] `

**Comment by melsawy** [comment]
@caiosba I added a new mapping for `report_language` as fact check field not enough to allow user filter by report language

**Comment by caiosba** [comment]
> @caiosba I added a new mapping for `report_language` as fact check field not enough to allow user filter by report language

Why? The report language should be always the same as the fact-check language, no?

**Review by caiosba — COMMENTED** [review]
@melsawy , it's just not clear to me why we need both report language and fact-check language since those two should always be the same.

**Comment by melsawy** [comment]
> @melsawy , it's just not clear to me why we need both report language and fact-check language since those two should always be the same.

Some times user create the fact check without publish a report so in this case we have a `FactCheck` language but there is no `Report` language

**Pull request merged**
