### PR TITLE
CV2-4794-remove travis.yml for CI

### PR DESCRIPTION
**Pull request by chinelo-obitube**
## Description

As part of the migration to github actions, we are removing .travis.yml 

References: https://meedan.atlassian.net/browse/CV2-4794

## How has this been tested?

we now have the workflow in github actions and the tests run on pull requests to develop and on push to master.

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Comment by caiosba** [comment]
@chinelo-obitube I think we should remove the `.travis.yml` only when we have all Travis functionality replaced by GitHub Actions, for example:

- Notifications
- Code coverage reporting to Code Climate

**Review by caiosba — CHANGES_REQUESTED** [review]
@chinelo-obitube I think we should remove the `.travis.yml` only when we have all Travis functionality replaced by GitHub Actions, for example:

- Notifications
- Code coverage reporting to Code Climate

They are not in place yet, right?

In other words, I think this should be the last step :)

**Comment by chinelo-obitube** [comment]
> @chinelo-obitube I think we should remove the `.travis.yml` only when we have all Travis functionality replaced by GitHub Actions, for example:
> 
> * Notifications
> * Code coverage reporting to Code Climate
> 
> There are not in place yet, right?
> 
> In other words, I think this should be the last step :)

Notifications already come to slack in the #1959 check-github channel. Monitoring for code climate because it's not specifically tied to travis. Once the jobs finish, I will check for the code climate results.

**Review by caiosba — APPROVED** [review]
Looks great, and I also checked the output in GitHub Actions to confirm that coverage is correctly merged and submitted to Code Climate! I just left one minor comment, please fix it before merging. Also, please replace the S3 bucket name as we discussed in the ticket, before merging.

**Comment by chinelo-obitube** [comment]
Branch is ready for another review. Changed the tests bucket to a new one.

**Review by caiosba — APPROVED** [review]
Great work @chinelo-obitube ! Looks great to me now!

**Pull request merged**
