### PR TITLE
5607 – Data dashboard table initial state should be an empty table

### PR DESCRIPTION
**Pull request by vasconsaurus**
## Description

Before we would return `nil`, meaning no table would be displayed.
Since we always want to display the table, even if it's empty, we need to return a structure.

### Notes
- I had to add the `team.default_language` so the first row would be displayed, and not only the header.
- Three hyphens are showing by the side of the export button (they are highlighted in the video below). I think I might need to fix it on the front-end side. But I'm not sure how we want to deal with it.

### Video
https://github.com/user-attachments/assets/184de1c5-7455-4186-a587-d14a878ce91b

References: CV2-5607

### Notes
- I added a new test to make sure we are returning all the columns
- I updated the older tests to check if Month has an hyphen, instead of `data_report` being `nil`. This still makes sure we are starting from an empty `data_report`.

### Tests
should return an existing empty data report structure if no statistics exist
`rails test test/models/team_test.rb:1133` 
 
should default to Rails cache for data report if monthly team statistics not present
`rails test test/models/team_test.rb:1164`
 
should return data report with chronologically ordered items, preferring the MonthlyTeamStatistics when present
`rails test test/models/team_test.rb:1172`

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Comment by vasconsaurus** [comment]
@caiosba when you have some time, can you take a look at this and see if it makes sense?
If this makes sense, and is in the correct direction, a question: What do you think is the best way to deal with the three hyphens that show by the side of the export button? (image below)

Screenshot 2024-11-27 at 17 04 26

**Comment by caiosba** [comment]
@vasconsaurus , let's look into it together in our 1:1 - I want to find a way where we don't need to repeat the column names. But yes, the direction is correct! For the three dots in the UI, it may require a simple fix on the frontend side.

**Comment by vasconsaurus** [comment]
@caiosba 

> a way where we don't need to repeat the column names

I kept thinking about this yesterday after I was done for the day, there is a method in `MonthlyTeamStatistic` we can use. So I updated it to do that.

**Comment by vasconsaurus** [comment]
@caiosba regarding tests, just to confirm:

- I think the tests are running twice?
    -  Build and Run Tests / unit-tests (pull_request) – This one had one failing test.
    - Build and Run Tests / unit-tests (push) – The tests failed to run.
- This test failed, but seems unrelated: `CheckS3Test#test_should_manage_files_in_S3 [/app/test/lib/check_s3_test.rb:22]`

Should we be running those two? If yes, then should I re-run the one that didn't run?
Is this failing test the flaky one you were talking about earlier, or should I worry about it?

**Comment by caiosba** [comment]
> I think the tests are running twice?

Hum... good point... @chinelo-obitube is this expected?

> Is this failing test the flaky one you were talking about earlier, or should I worry about it?

Seems unrelated to your changes, but it's not the one I was talking about... so, since we're not in a hurry, I suggest you just re-run.

**Pull request merged**
