### PR TITLE
CV2-4069 fix a few broken paths that are now mistakenly trying to add items rather than search for them

### PR DESCRIPTION
**Pull request by DGaffney**
## Description

I missed a few paths when changing everything to POST-only - this is a small tweak to accommodate.

References: 4069

## How has this been tested?

I believe this shouldn't change any tests, since all previous tests worked fine and we deployed off that, but will fix if it comes up!

## Things to pay attention to during code review

Triple check I got the rest of these?

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Review by caiosba — APPROVED** [review]
Looks good to me. I reviewed all cases from here:

```
check-api$ vim -p $(grep -rl '/similarity' app lib config)
```

Let's just wait for CI before merging since maybe some mocks need to be updated.

**Review by skyemeedan — APPROVED** [review]
Is there a test that covers this behavior?

**Comment by DGaffney** [comment]
> Is there a test that covers this behavior?

Presumably, the functionality that tests these exact functions should be stubbed at the request level rather than at the `Bot::Alegre` level which is where I think they're stubbed currently. I'd rather get this out and follow up with a better test post deploy - @caiosba how would you like to proceed?

**Comment by caiosba** [comment]
I think we're good to go. The tests here are mocked, the real tests are on the integration tests side.

**Comment by caiosba** [comment]
> > the real tests are on the integration tests side.
> > but since we deployed the bug without test failure, it seems like they don't cover this problem?

Yes, we don't. This is a problem we currently have... we don't really test (integration test, end-to-end) the tipline interactions (mainly because it would be hard to automate remote-control of WhatsApp Web, for example). This is why the bug was just identified from real tipline requests and not captured by the current integration test (which covers items created using the web client, in which the bug doesn't happen) or by the current unit tests (which mock the Alegre responses).

**Pull request merged**
