### PR TITLE
#8266 Upgrade Elasticsearch to 7.9.1

### PR DESCRIPTION
**Pull request by huslage**

### CODE REVIEW

**Comment by huslage** [comment]
@melsawy the Elastic Cloud version got updated to 7.9.2 over the weekend. You may want to change your testing versions to match.

**Comment by melsawy** [comment]
OK @huslage 
FYI: I am using this branch https://github.com/meedan/check-api/pull/636 for upgrading

**Comment by huslage** [comment]
Can we close this one then?

**Comment by melsawy** [comment]
Yes

**Comment by huslage** [comment]
Dupe of #636

**Pull request closed without merging**
