### PR TITLE
Add API documentation for `set_original_claim`

### PR DESCRIPTION
**Pull request by jayjay-w**
## Description

Add API documentation for `set_original_claim` in the `createProjectMedia` mutation.

References: CV2-4676

## How has this been tested?

Confirmed that the changes are well formatted and the query example works.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Comment by caiosba** [comment]
Thanks @jayjay-w , and please remember to update the documentation here too: https://github.com/meedan/check/wiki/GraphQL-query-examples#create-fact-check

**Comment by vasconsaurus** [comment]
I have a tiny nitpick/suggestion, feel free to ignore it.
I would change line 272 so that the heading is in the same hierarchy as the `Create medias` (https://github.com/meedan/check-api/blob/8bbfb889ded19e3e65f1e367f48ab55210db6844/doc/api-user.md?plain=1#L272)
```
## Create media with original claim
```

—
Seemingly unrelated to this PR, but in this link: https://github.com/meedan/check/wiki/GraphQL-query-examples#create-fact-check

I would move `Create original claim when creating fact check` to the `Create fact-check` section. And add it as a last item there, `Create a fact-check with an original claim`, instead of leaving it under `Update a fact-check`. 

Screenshot 2024-07-08 at 08 44 15

**Review by vasconsaurus — APPROVED** [review]

**Comment by vasconsaurus** [comment]
Thanks @jayjay-w! Looks great 🚀

**Comment by caiosba** [comment]
@jayjay-w we need this in `develop` (no need to revert the merge to `master` though)

**Pull request merged**
