### PR TITLE
3995 – Invite a new user to a shared feed

### PR DESCRIPTION
**Pull request by vasconsaurus**
## Description

We are improving feed invitation and inviting a new user who is part of 2 different workspaces to a shared feed.
The new user's workspaces are both empty.

References: 3995, 3884

## How has this been tested?

By running the seed's script.

## Notes

- Once this is merged, I'll update the confluence page.
- I split the big data hash we had with everything into smaller groups (2 hashes and 1 array): data_users, data_items and data_imported_fact_checks. I thought this made it easier to reason with.

### CODE REVIEW

**Comment by vasconsaurus** [comment]
@brianfleming it's been a while 😁 Could you take a look at this one and see if there is anything I might have missed? For this one we wanted to keep it simple.

**Comment by brianfleming** [comment]
> @brianfleming it's been a while 😁 Could you take a look at this one and see if there is anything I might have missed? For this one we wanted to keep it simple.

great @vasconsaurus I will check it out today. i am traveling to the meedan offices this week so it might take me a min to get to it. 
Question, should I run the whole thing fresh or is it ok to do the add more data option? just want to make sure I see the correct info

**Comment by vasconsaurus** [comment]
> great @vasconsaurus I will check it out today. i am traveling to the meedan offices this week so it might take me a min to get to it. Question, should I run the whole thing fresh or is it ok to do the add more data option? just want to make sure I see the correct info

Both should work. So you can use the add more data option. It will add more data to the specified user, create a new shared feed, new invited user (with 2 empty workspaces), and invite said user. (then you can log in to the invited user account and accept or decline the invitation)

**Comment by brianfleming** [comment]
get ready for a couple of my usual tiny picky requests @vasconsaurus !!
- [ ] for the other workspace, can you give it a different workspace logo than the rails logo, so each workspace has a unique image? Would just help differentiating them and being more "real world"
- [ ] For the shared feed names, any way to name them something where we can know a bit more about where they were created? I have no good suggestion on this, but just like the logo thing, trying to make it more readable?

Let me know if those make sense.

**Comment by vasconsaurus** [comment]
> get ready for a couple of my usual tiny picky requests @vasconsaurus !!
> 
> * [ ]  for the other workspace, can you give it a different workspace logo than the rails logo, so each workspace has a unique image? Would just help differentiating them and being more "real world"
> * [ ]  For the shared feed names, any way to name them something where we can know a bit more about where they were created? I have no good suggestion on this, but just like the logo thing, trying to make it more readable?
> 
> Let me know if those make sense.

I think it makes sense and shouldn't be issue. I'll work on both

**Comment by vasconsaurus** [comment]
@brianfleming 

1. **Teams:** To make it easier to differentiate the teams:
    a. Added the different avatars/logos for each team. 
    b Also added 'main user: main team' and 'invited user: team 1', 'invited user: team 2' to the team's name.
2. **Feeds:** To make it easier to identify the feed:
    a. We are now counting which feed it is, and adding the number
    b. Added the user name and team
3. **Lists:** Ended up also updating when we create lists, so we don't create the same list all the time. So we can create multiple feeds, but are only creating one list.

**1. Teams**
Screenshot 2023-12-15 at 09 45 27
Screenshot 2023-12-15 at 09 44 22

**2. Feeds**
Screenshot 2023-12-15 at 10 08 34
Screenshot 2023-12-15 at 10 09 28

**3. Lists**
Screenshot 2023-12-15 at 10 40 18

**Review by caiosba — APPROVED** [review]

**Pull request merged**
