### PR TITLE
New get_language_detection field

### PR DESCRIPTION
**Pull request by amoedoamorim**
This adds a field get_language_detection to the graphql Team type and and language_detection field to the mutation and a setter to the Team model.
And changes logic in smooch_languages.rb to only have Alegre autodetect message if this new setting is enabled.

### CODE REVIEW

**Review by caiosba — APPROVED** [review]
Looks good so far!

**Comment by amoedoamorim** [comment]
How do we make this `language_detection` field initialize as `true`?

**Comment by caiosba** [comment]
> How do we make this `language_detection` field initialize as `true`?

Hum... in that case, it's better to use the opposite (`no_language_detection`)

**Comment by amoedoamorim** [comment]
> > How do we make this `language_detection` field initialize as `true`?
> 
> Hum... in that case, it's better to use the opposite (`no_language_detection`)

Not sure I'm following here. Is this ruby magic or do you actually mean I should invert the implementation logic?

**Comment by caiosba** [comment]
> > > How do we make this `language_detection` field initialize as `true`?
> > 
> > 
> > Hum... in that case, it's better to use the opposite (`no_language_detection`)
> 
> Not sure I'm following here. Is this ruby magic or do you actually mean I should invert the implementation logic?

Invert the logic, in a way that is not weird but that we don't need to set it as `true` for existing and new teams.

**Review by caiosba — APPROVED** [review]

**Pull request merged**
