### PR TITLE
Articles data model and API changes

### PR DESCRIPTION
**Pull request by caiosba**
API changes to return filtered and sorted explainers and fact-checks for a given workspace.

Reference: CV2-4441.

Check Web Epic PR: https://github.com/meedan/check-web/pull/1951

### CODE REVIEW

**Comment by caiosba** [comment]
@melsawy can you please review this?

**Review by melsawy — APPROVED** [review]

**Comment by brianfleming** [comment]
@caiosba I pulled down the latest on this branch and the web side and now I don't see any fact-checks in the articles list. Is this related to the most recent push? Since its local, should I rerun the seeds file? Just want to see if there is a bug here or not

**Comment by caiosba** [comment]
> @caiosba I pulled down the latest on this branch and the web side and now I don't see any fact-checks in the articles list. Is this related to the most recent push? Since its local, should I rerun the seeds file? Just want to see if there is a bug here or not

Yes, this is related to latest changes that now require a `team_id` attribute in the fact-checks claims for filtering. It should work for claims/fact-checks you create from now on, but for existing ones you need to run an update in Rails console.

**Comment by brianfleming** [comment]
> > @caiosba I pulled down the latest on this branch and the web side and now I don't see any fact-checks in the articles list. Is this related to the most recent push? Since its local, should I rerun the seeds file? Just want to see if there is a bug here or not
> 
> Yes, this is related to latest changes that now require a `team_id` attribute in the fact-checks claims for filtering. It should work for claims/fact-checks you create from now on, but for existing ones you need to run an update in Rails console - let me know if you want to do the latter and I can show you how to do so.

yeah, that would be awesome. just let me know what commands to run.
Will the seeds file script also result in the "correct" view?

**Comment by caiosba** [comment]
> > > @caiosba I pulled down the latest on this branch and the web side and now I don't see any fact-checks in the articles list. Is this related to the most recent push? Since its local, should I rerun the seeds file? Just want to see if there is a bug here or not
> > 
> > 
> > Yes, this is related to latest changes that now require a `team_id` attribute in the fact-checks claims for filtering. It should work for claims/fact-checks you create from now on, but for existing ones you need to run an update in Rails console - let me know if you want to do the latter and I can show you how to do so.
> 
> yeah, that would be awesome. just let me know what commands to run. Will the seeds file script also result in the "correct" view?

```
docker-compose exec api bundle exec rails c

ClaimDescription.each { |cd| cd.team_id ||= cd.project_media&.team_id ; cd.save! } ; nil
```

For the seeds file, we need to do some work to create some standalone fact-checks, but I captured that in the ticket already.

**Comment by brianfleming** [comment]
> > > > @caiosba I pulled down the latest on this branch and the web side and now I don't see any fact-checks in the articles list. Is this related to the most recent push? Since its local, should I rerun the seeds file? Just want to see if there is a bug here or not
> > > 
> > > 
> > > Yes, this is related to latest changes that now require a `team_id` attribute in the fact-checks claims for filtering. It should work for claims/fact-checks you create from now on, but for existing ones you need to run an update in Rails console - let me know if you want to do the latter and I can show you how to do so.
> > 
> > 
> > yeah, that would be awesome. just let me know what commands to run. Will the seeds file script also result in the "correct" view?
> 
> ```
> docker-compose exec api bundle exec rails c
> 
> ClaimDescription.each { |cd| cd.team_id ||= cd.project_media&.team_id ; cd.save! } ; nil
> ```
> 
> For the seeds file, we need to do some work to create some standalone fact-checks, but I captured that in the ticket already.

no joy running that command @caiosba , here is the output:

```
irb(main):002:0> ClaimDescription.each { |cd| cd.team_id ||= cd.project_media&.team_id ; cd.save! } ; nil

/usr/local/bundle/gems/activerecord-6.1.7.8/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `each' for ClaimDescription:Class (NoMethodError)
```

**Comment by caiosba** [comment]
> ClaimDescription.each { |cd| cd.team_id ||= cd.project_media&.team_id ; cd.save! } ; nil

Sorry (now I tested!)

```
ClaimDescription.where(team_id: nil).each { |cd| cd.update_column(:team_id, cd.project_media&.team_id) } ; nil
```

**Pull request merged**
