### PR TITLE
CV2-3738: remove the privacy permissions

### PR DESCRIPTION
**Pull request by melsawy**
## Description

Remove the privacy permissions related to projects since we are showing items in lists instead of folders.

References: CV2-3738

## How has this been tested?

As folders not exists on our app we can use existing items to verify this one like https://checkmedia.org/iverify-kenya/media/2149504

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Review by caiosba — CHANGES_REQUESTED** [review]
@melsawy we need to fix the logic here too: https://github.com/meedan/check-api/blob/develop/lib/check_search.rb#L354

**Review by caiosba — COMMENTED** [review]
Assign for review again after tests pass again, please :)

**Comment by melsawy** [comment]
@caiosba the failure is a flaky test and same failure here https://app.travis-ci.com/github/meedan/check-api/jobs/610397741
so please review while I am fixing this one

**Review by caiosba — APPROVED** [review]
Thanks, Sawy! Good to go once tests pass.

**Pull request merged**
