### PR TITLE
Be able to export a full list of media clusters.

### PR DESCRIPTION
**Pull request by caiosba**
## Description

The current export limit for media lists is 10.000 because this is the maximum size of a result window in ElasticSearch. The solution is to paginate the results.

Fixes: CV2-5205.

## How has this been tested?

This is just a refactoring, the existing test should cover it.

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Review by melsawy — CHANGES_REQUESTED** [review]
@caiosba to get all existing items not recommended to use pagination as maximum item to get through pagination is 10.000 items but you should search `search_after` option [this is a reference to get items using search_after](https://github.com/meedan/check-api/blob/develop/lib/tasks/migrate/20210223101154_sync_items_between_es_and_pg.rake#L20-L35 )

**Comment by caiosba** [comment]
Thanks Sawy, I'll make this change!

**Comment by DGaffney** [comment]
As long as this offset/limit syntax works it otherwise looks good to me:

```
      search.set_option('eslimit', page_size)
      search.set_option('esoffset', offset)
```

**Review by DGaffney — APPROVED** [review]

**Comment by caiosba** [comment]
> @caiosba to get all existing items not recommended to use pagination as maximum item to get through pagination is 10.000 items but you should iterated using `search_after` option [this is a reference to get items using search_after](https://github.com/meedan/check-api/blob/develop/lib/tasks/migrate/20210223101154_sync_items_between_es_and_pg.rake#L20-L35)

Thanks @melsawy ! Indeed, I tested it locally with more than 20.000 items and my previous approach only exported 10.000, with no alerts from ElasticSearch. I re-implemented it using `search_after` and then I was able to export more than 20.000 items in less than 15 minutes locally. Thanks a lot for the reference you provided, it helped me a lot!

Kindly re-review, @melsawy :)

**Review by melsawy — APPROVED** [review]
LGTM and I suggest to use `do..whileLoop` instead of `while true`  to fix [CC issue](https://codeclimate.com/github/meedan/check-api/pull/2024#)

**Pull request merged**
